apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pipeline-app-stage

resources:
  - ../../base
  - route.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: pipeline-app-final
