apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-app-final
  labels:
    app: pipeline-app-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-app-final
  template:
    metadata:
      labels:
        app: pipeline-app-final
    spec:
      containers:
        - name: pipeline-app-final
          # Use the immutable SHA digest here instead of :latest
          image: ocp-real-registry-quay-openshift-operators.apps.cluster-realip.zeteq.com/zahid/pipeline-app-final@sha256:d6b7e84502e290ce5db695ff8693ac8987fc451ce2f4a278d73c07ff54bd2a0b
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
